# Generated by Django 5.2.16 on 2026-08-06 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
            },
        ),
        migrations.AlterModelOptions(
            name="userpersonality",
            options={"verbose_name": "사용자 성격", "verbose_name_plural": "사용자 성격"},
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남성"), ("F", "여성"), ("O", "기타"), ("N", "선택 안함")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userpersonality",
            name="active_relaxed",
            field=models.IntegerField(
                blank=True,
                help_text="1=활동적, 5=여유로운",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userpersonality",
            name="introvert_extrovert",
            field=models.IntegerField(
                blank=True,
                help_text="1=내향적, 5=외향적",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userpersonality",
            name="planning_spontaneous",
            field=models.IntegerField(
                blank=True,
                help_text="1=계획적, 5=즉흥적",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userpersonality",
            name="values_description",
            field=models.TextField(
                blank=True, help_text="개인 가치관에 대한 자유 텍스트 설명", max_length=500
            ),
        ),
    ]
