# Generated by Django 5.2.16 on 2026-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_userpersonality_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_adult_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="kakao_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
    ]
