# Generated by Django 5.2.16 on 2026-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_adult_verified_user_kakao_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
