# Generated by Django 5.2.16 on 2026-07-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interest",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="matching.interestcategory",
            ),
        ),
        migrations.AddField(
            model_name="matchingrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matching_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchingresult",
            name="matched_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchingresult",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="matching.matchingrequest",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="matching_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connections",
                to="matching.matchingresult",
            ),
        ),
        migrations.AddField(
            model_name="userinterest",
            name="interest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interests",
                to="matching.interest",
            ),
        ),
        migrations.AddField(
            model_name="userinterest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="interest",
            index=models.Index(fields=["category", "name"], name="interests_categor_eab6b3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="interest",
            unique_together={("category", "name")},
        ),
        migrations.AddIndex(
            model_name="matchingrequest",
            index=models.Index(
                fields=["requester", "status"], name="matching_re_request_1816b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchingrequest",
            index=models.Index(
                fields=["status", "created_at"], name="matching_re_status_2441d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchingresult",
            index=models.Index(
                fields=["request", "-total_score"], name="matching_re_request_29364c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchingresult",
            index=models.Index(
                fields=["matched_user", "is_contacted"], name="matching_re_matched_eadcd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchingresult",
            index=models.Index(fields=["total_score"], name="matching_re_total_s_0789e2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="matchingresult",
            unique_together={("request", "matched_user")},
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["from_user", "status"], name="connections_from_us_3cd30e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(fields=["to_user", "status"], name="connections_to_user_35dc96_idx"),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["status", "created_at"], name="connections_status_1bbefe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("from_user", "to_user")},
        ),
        migrations.AddIndex(
            model_name="userinterest",
            index=models.Index(fields=["user", "level"], name="user_intere_user_id_4851d0_idx"),
        ),
        migrations.AddIndex(
            model_name="userinterest",
            index=models.Index(fields=["interest", "level"], name="user_intere_interes_98de12_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userinterest",
            unique_together={("user", "interest")},
        ),
    ]
