# Generated by Django 5.2.16 on 2026-08-06 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connection",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "연결",
                "verbose_name_plural": "연결",
            },
        ),
        migrations.AlterModelOptions(
            name="interest",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "관심사",
                "verbose_name_plural": "관심사",
            },
        ),
        migrations.AlterModelOptions(
            name="interestcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "관심사 카테고리",
                "verbose_name_plural": "관심사 카테고리",
            },
        ),
        migrations.AlterModelOptions(
            name="matchingrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "매칭 요청",
                "verbose_name_plural": "매칭 요청",
            },
        ),
        migrations.AlterModelOptions(
            name="matchingresult",
            options={
                "ordering": ["-total_score", "-created_at"],
                "verbose_name": "매칭 결과",
                "verbose_name_plural": "매칭 결과",
            },
        ),
        migrations.AlterModelOptions(
            name="userinterest",
            options={
                "ordering": ["-level", "interest__category"],
                "verbose_name": "사용자 관심사",
                "verbose_name_plural": "사용자 관심사",
            },
        ),
        migrations.AlterField(
            model_name="connection",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "대기중"),
                    ("ACCEPTED", "수락됨"),
                    ("REJECTED", "거절됨"),
                    ("BLOCKED", "차단됨"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interestcategory",
            name="icon",
            field=models.CharField(blank=True, help_text="아이콘 이름 또는 이모지", max_length=50),
        ),
        migrations.AlterField(
            model_name="matchingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "대기중"),
                    ("PROCESSING", "처리중"),
                    ("COMPLETED", "완료"),
                    ("CANCELLED", "취소됨"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="matchingresult",
            name="matching_reason",
            field=models.TextField(
                blank=True, help_text="이 사용자들이 매칭된 이유에 대한 AI 생성 설명"
            ),
        ),
        migrations.AlterField(
            model_name="userinterest",
            name="level",
            field=models.IntegerField(
                default=3,
                help_text="1=초보/궁금함, 3=중급, 5=전문가/열정적",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
