# Generated by Django 5.2.16 on 2026-08-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="admin_reply",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
